name: Lint

on: [pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1024
      - uses: actions/setup-python@v2
      - name: pre-commit
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha}}
          HEAD_SHA: ${{ github.event.pull_request.head.sha}}
        run: |
          python -m pip install pre-commit
          pre-commit run --from-ref $BASE_SHA --to-ref $HEAD_SHA --all-files
